### ISSUE TITLE
Failed to compile due to too old dependencies on Flutter

### ISSUE THREAD

**Issue by NineWoranop** [jcrisp88/flutter-webrtc_python-aiortc-opencv#4]
Hello,

I failed to get the dependencies on this flutter example. The dependencies are too old. They are no longer there for compile.
Could you please help me to upgrade your example if you have time?

**Comment by 0010SS** [comment]
Simply changing the dependency versions make the repo work for me. Below is my setup for `pubspec.yaml`:
```
environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  flutter_webrtc: ^0.9.47
  http: ^1.1.0
  equatable: ^2.0.5
```
